### ISSUE TITLE
Support Decorators

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/slowloris#46]
I need support for Python decorators.  A Python example is:

```
@some_decor
def cube(n):
    return n * n *n
```

The SlowLoris parallel would be:

```
(@some_docor
(def cube
    (lambda (n)
        (* n n n))))
```

**Comment by marqov** [comment]
Hi !
Can I work on this feature ?
Thanks !

**Comment by theJollySin** [comment]
@marqov Sure!  There's a lot of work left on Slow Loris.  Try it out and give me a pull request when you have something.

**Comment by marqov** [comment]
@theJollySin Can you review my PR !! Sorry for my late PR

**Comment by theJollySin** [comment]
Sorry, I will look at it.  I was out of town for a week.  I did not mean to ignore you.

**Comment by theJollySin** [comment]
Your implementation looks good, I like it. Pull request accepted.

How would you feel if I migrated the project from Python 2 to Python 3?  I am *guessing* that would be easier for most people.

**Comment by marqov** [comment]
Hi John,
I would like to thank you for you review !! It is my first time in open
source world and I like your projects :)
I will try to do this weekend the task of migration to Python3 !

Thank you very much :)

**Comment by theJollySin** [comment]
Hello again,

Ah, that's awesome. Welcome. 

Looking at the interface for GitHub tickets it seems I can't assign this ticket to you. But you can, of course, just complete the task and submit a Pull Request. So, that appears to be how the GitHub interface will work. I'll see if there is a way to submit a ticket directly to you, but I only seem to have the power to assign taskst o me.  Still, please give it a whirl!
